# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: API

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  SECRET_KEY: 202de8ade95f37eb8bc630d47c1fe140fb573fe5ce7dc3f4a7468811388b1a64
  DATABASE_URL: postgres://mpxrlglzqkjjpl:30270589932f8a763e7c43e6e4b5d4d9c63a7807e69e3654696ba08cf418c0b2@ec2-54-80-122-11.compute-1.amazonaws.com:5432/d9v0nli5clfsup
  DB_USER: mpxrlglzqkjjpl
  DB_PASS: 30270589932f8a763e7c43e6e4b5d4d9c63a7807e69e3654696ba08cf418c0b2
  DB_NAME: d9v0nli5clfsup
  DB_PORT: 5432
  DB_HOST: ec2-54-80-122-11.compute-1.amazonaws.com
  JWT_SECRET_KEY: fbe1fcc143774486d154fb3ff2a7e3a464a46a8e4917dc1d4adf63f4f2cbeec9
  JWT_ALGORITHM: HS256
  JWT_EXPIRATION_MINUTES: 30
  JWT_REFRESH_EXPIRE_HOURS: 12


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.8.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install autopep8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with autopep8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        pytest
